### ISSUE TITLE
Full profile page

### ISSUE THREAD

**Issue by tonylomax** [fac-17/UpSkillMe#20]
Relates #19
Relates #18
Relates #17
Relates #16 

- [x] Function: Retrieve all user profile information from Airtable (username, avatar(generic), total points)
- [x] Function: Add all points from each badge and display - point score x 8
- [x] Create profile detail component (img, name/username, points)
- [x] Render profile detail component
