### ISSUE TITLE
Create basic logon page

### ISSUE THREAD

**Issue by tonylomax** [fac-17/UpSkillMe#54]
- [x] Create new logon component
- [x] React routes package to conditionally render logon pages
- [x] On the profile page, add a logout button linking back to this
- [x] Prevent people signing up more than once
