### ISSUE TITLE
Opportunities page

### ISSUE THREAD

**Issue by tonylomax** [fac-17/UpSkillMe#64]
- [x] Create airtable table with opp details
- [x] Create oppotunities page component
Create list component that contains opp detail:
- [x] Organisation
- [x] Type of activity
- [x] Time
- [x] Date 
- [x] Location
- [x] Link to further information
